### ISSUE TITLE
Can't get past Server select screen

### ISSUE THREAD

**Issue by AstralPhnx** [Arrowgene/Arrowgene.Ez2Off#1]
Firstly I'm unsure if this is a bug caused by the fact that this is a work in progress or if it is a bug with the program but after compiling and starting the server application I then started the version of ez2on I downloaded from the readme. Everything works fine but once I select a server the game just... doesn't do anything and just sticks on the mode select menu. Any ideas?

**Comment by sebastian-heinz** [comment]
Hello, 

Im sorry the readme might be misleading as it sounds this is completed.
To clear things up, this project is not completed and is only a base.

So far there are only three types of packets handled:

FIle: EzServer.cs

```
        private void LoadHandles()
        {
            this.handle.AddHandler(new Login(this));
            this.handle.AddHandler(new SelectMode(this));
            this.handle.AddHandler(new SelectServer(this));
        }

```

the handles can be found in the EzHandle folder including one Blank Handle which can be copied to implement new handles.

You can set a breakpoint inside the Received-method:

File: EzHandle.cs

```
        public void Received(EzClient client, ByteBuffer data)
        {
            EzPacket request = client.PacketBuilder.Process(data);
```

to break on incoming data, 
and you will notice that only packets will be handled with a known packetId

this means u need to create a new handler class and load it for packetIds which are not implemented.

This is hard when you don't know what to respond with, and since the official server is gone a lot of this is guessing. But there is also a program called "ez solista' which responses with some valid packets, and lets you infact play the game.

so if u wish to help you are greatly welcome, if you just wish to play i will try and get a guide up in the readme on how you can use solisra to play the game. and also use solista to enhance the functionality of this project

Edit; i think there is a solista.exe, this should be a server for singleplay. but it might be incompatible with the provided version of the client. as i mentioned i will try improove the readme and get tutorials up here. ;) thank you for your interest

Best Regards

**Comment by AstralPhnx** [comment]
Ah I see. Thanks for getting back to me! I have the files sitting on my computer for EZ2ON reboot actually if you wanted to try modify the server in order to work with reboot. Only issue is the exe is packed using VMProtect so that might be a bit interesting to unpack

**Comment by sebastian-heinz** [comment]
Yes that would be good, I also have ez2onRe but I feel like my files are broken. It crashes with win 8.1 not sure if its windows xprotect related. So if u have untouched ez2onRe I'd be greatly interested.

**Comment by AstralPhnx** [comment]
No problem. I'll upload that for you asap. It's 3.30 gigabytes in size. I'd love to see reboot get an offline server solution myself so I'll help however I can

**Comment by sebastian-heinz** [comment]
Nice, No Worries, take your time. My Reboot only seems to be 1.2GB, maybe its an early version. I was already looking into breaking XTrap but the .exe keept crashing on my system. So im really excited if we can manage to get your version to work somehow. 

Does the "Ez Solista.exe" work for you?, when u start it (maybe as Admin) and use it to start the Game?

Best Regards

**Comment by Aukubi** [comment]
Hi, I saw that tuxduxe143 actually have a copy of EZ2ON - Reboot.
I'll be really intersted if you can send me a link for download it, I'm searching for this game everywhere but can't find it.

Best regards

**Comment by sebastian-heinz** [comment]
In the readme.md file you can find a mega link to a version of ez2on. But I suspect it's not the latest and I would also be interested in the latest client version of ez2on

**Comment by Aukubi** [comment]
I can't start the game, it is simply not working ...
When I launch it, I have an information pop-up and if i select "Yes" it crash and if I select "No", it's the same

**Comment by sebastian-heinz** [comment]
You need to start the server. Its an online game, the server is gone, this project is about making a server for the game so you can play again. This project is not completed so you can not expect to play yet. But you can move past the 'yes/no' screen and get to the channel selection if you run the server application. I updated the Readme.MD file to give instructions how to run the server under Windows and OSX.

**Comment by avelinocr** [comment]
Hey, do you guys still need the game files?

**Comment by sebastian-heinz** [comment]
Yes, Id love to have the latest possible game files of Ez2On Reboot!
This will allow to provide a download link for all people who stumble across this, and open the chance to make a server for the latest official version that was released before it got closed.

**Comment by Aukubi** [comment]
Yes, I would love to have the lastest EZ2ON Reboot files !

**Comment by avelinocr** [comment]
Please e-mail me at avelinocr@gmail.com or contact me on skype avelinocr22

**Comment by ljsoo** [comment]
so how would i get this in game play? creating room makes the game crash.

also instructions same as mac for windows:
set directory
dotnet restore
dotnet run

**Comment by sebastian-heinz** [comment]
Please read from the beginning.
> To clear things up, this project is not completed and is only a base.

This is work in progress.

**Comment by sebastian-heinz** [comment]
Some small update
- Unpacking Data from Ez2On beta is possible
- Getting into the lobby 

https://www.youtube.com/watch?v=pTzMn7lFBc0&feature=youtu.be

**Comment by Aukubi** [comment]
Awesome man, keep up the good work !
Just ask me if you want to test something or anything ;)
