### ISSUE TITLE
Fix Battle Meter

### ISSUE THREAD

**Issue by CHFreezer** [Arrowgene/Arrowgene.Ez2Off#4]
In GameBattleMeter.cs, only the client sends the packet to the server, I hope that the client can correctly receive the packet and synchronize the score when playing. So I would like to ask the server what format to create this packet?
![sr_ q ye rzwb vt2r1g](https://user-images.githubusercontent.com/28268343/45383635-5f6ce600-b63e-11e8-9b54-a2a6ac8ea009.png)

**Comment by sebastian-heinz** [comment]
Hi thank you for the interest, but at the moment I can not help with it due to limited time.

I think it would boil down to the following tasks:
1) The individual bytes need to be identified so we know the meaning
2) Find the correct packetId to use as a response
3) Find the correct data structure to respond

If you find a solution and create a PR I would be happy to merge that so its available for everyone.

**Comment by CHFreezer** [comment]
Is this question in your TODO list?

**Comment by sebastian-heinz** [comment]
No but as this is a github issue it will be visible to everyone and whoever feels comfortable can fix it.
The TODO-file is a bit outdated tho

**Comment by wtfliru** [comment]
I would be interested looking into this project. If you want please reach out to me on Discord @ pasta#0531

I will also take a look at R14

**Comment by sebastian-heinz** [comment]
Code has been updated to r14, battle meter works in both r13 and r14 version, closing
