### ISSUE TITLE
ez2off data gui tool directions for use??

### ISSUE THREAD

**Issue by zzcc1002** [Arrowgene/Arrowgene.Ez2Off#6]
@ai in the music folder.I want to modify the pattern after choosing dat, how should I order it?

**Comment by sebastian-heinz** [comment]
You can use this tool: https://github.com/Arrowgene/Arrowgene.StepFile for extracting and repacking game files. You can open `Music/*.dat` files and `EzData.tro` with this tool. There is also a tool to convert .pt files to .ez files.

**Comment by zzcc1002** [comment]
![추출](https://user-images.githubusercontent.com/68997673/101759934-8f590b80-3b1d-11eb-9c7e-93ef525b5f37.png)
arrowgene.stepfile.exe
1.picture
Extracted to  EzData.tro file. by 6-@ai-ez.bin

2.error
![에러](https://user-images.githubusercontent.com/68997673/101759939-908a3880-3b1d-11eb-81c9-17e114d50cc4.png)
6-@ai-ez.bin load error

**Comment by sebastian-heinz** [comment]
Which client is this? The arrowgene client uses a different encryption and can not be unpacked with this tool.

https://mega.nz/#F!n88A1BjA!APvm7Sq9ILpcd3qZy-K4aQ

Here is a link to all the official versions, these should be able to be extract

You can see the tool says "Encryption: Unknown" so it can not work with these files

**Comment by zzcc1002** [comment]
Thank you. 

ez2on 3rd client down. 
I succeeded in extracting the data folder from EzData.tro and reading Data folder bin.
But I failed to read the sound file bin and ptn files.
How can I solve this problem, my friend?

**Comment by sebastian-heinz** [comment]
The .bin files are the ones in EzData.tro/Data/*.bin i'm not sure about the music .bin files. If you click the 2nd icon it says "New bin file" and then can select a .bin file from disk (after extracted) to open.

It has been a while since I worked on this, so i don't quite remember. But it might not work with song .bin files, just the other ones. (Itemdata.bin etc)

As for .ptn files, i think there is a button to convert .ptn to .ez file. This tool can not graphically display the pattern files just convert.
